version: ‘3.5’

service:
  target:
    image: ‘target’
    container_name: target
    tty: true
    stdin_open: true
    command: bash
    network:
Cnet

  attack:
    image: ‘attack’
    container_name: attack
    tty: true
    stdin_open: true
    command: bash
    network:
Cnet
networks:
  Cnet:
    driver: bridge
