version: '3.5'

services:
  target:
    image: 'target'
    container_name: target
    tty: true
    stdin_open: true
    command: bash
    networks:
      - Cnet
      - docker-elk_elk

  attack:
    image: 'attack'
    container_name: attack
    tty: true
    stdin_open: true
    command: bash
    networks:
      - Cnet
networks:
  Cnet:
    driver: bridge
  docker-elk_elk:
    external: true
